window.CLYDE_DATA = {
  source: "Multiple verified sources",
  verified: [
    { id:"clyde-discord-inuzu", source:"Newgrounds", title:"Clyde (Discord)", artist:"Inuzu", tags:["clyde","discord","fanart","illustration"], url:"https://www.newgrounds.com/art/view/inuzu/clyde-discord", image:"https://art.ngfiles.com/images/2231000/2231669_inuzu_clyde-discord.jpg?f1639141665=", note:"Clyde artwork specifically titled Clyde (Discord)." },
    { id:"discord-samrunner", source:"Newgrounds", title:"Discord", artist:"SamRunner", tags:["clyde","discord","fanart","furry","furry-art","darkmode","lightmode"], url:"https://www.newgrounds.com/art/view/samrunner/discord", image:"https://art.ngfiles.com/images/2531000/2531864_samrunner_discord.png?f1653146054=", note:"Clyde Discord fanart with dark-mode and light-mode concepts." },
    { id:"anthro-clyde", source:"Newgrounds", title:"Anthro Clyde", artist:"LiquidCrystalBunny", tags:["anthro","discord","furry","furry-art","pixel-art"], url:"https://www.newgrounds.com/art/view/zaxolotl/anthro-clyde", image:"", note:"Anthro/furry interpretation of Discord's Clyde. Open the original page for the artwork." },
    { id:"discord-furry-lol", source:"Newgrounds", title:"Discord furry lol", artist:"DatsFunny", tags:["clyde","discord","discord-clyde","discord-furry"], url:"https://www.newgrounds.com/art/view/datsfunny/discord-furry-lol", image:"", note:"Newgrounds artwork explicitly tagged clyde, discord, discord-clyde, and discord-furry." },
    { id:"clyde-old", source:"Newgrounds", title:"Clyde (old)", artist:"chomperChomp", tags:["clyde","discord","mascot","illustration"], url:"https://www.newgrounds.com/art/view/chomperchomp/clyde", image:"", note:"Older Discord Clyde mascot artwork. The Newgrounds page contains an image." },
    { id:"robot-girl-clyde", source:"Newgrounds", title:"robot girl discord clyde", artist:"ItIsNowSoupTime", tags:["clyde","discord","robot","illustration"], url:"https://www.newgrounds.com/art/view/itisnowsouptime/robot-girl-discord-clyde", image:"https://art.ngfiles.com/images/834000/834311_itisnowsouptime_robot-girl-discord-clyde.webp", note:"Illustration explicitly titled around Discord Clyde; the Newgrounds page exposes an art image." },
    { id:"thanks-discord", source:"Newgrounds", title:"Thanks for the whole year (new discord server)", artist:"Nemuri18", tags:["clyde","clyde-discord","discord","discord-server"], url:"https://www.newgrounds.com/art/view/nemuri18/thanks-for-the-whole-year-new-discord-server", image:"", note:"Newgrounds artwork tagged with Clyde and Discord." },
    { id:"more-cat-discord", source:"Newgrounds", title:"More Cat of discoerddsdsds", artist:"BreadinatoArts", tags:["clyde-discord","discord"], url:"https://www.newgrounds.com/art/view/breadinatoarts/more-cat-of-discoerddsdsds", image:"", note:"Artwork tagged clyde-discord and discord on Newgrounds." },
    { id:"clyde-discordchan", source:"Newgrounds", title:"Clyde(discordchan from discord logo)", artist:"palmeritauwuy", tags:["clyde","discord","furry","cat","illustration"], url:"https://www.newgrounds.com/art/view/palmeritauwuy/clyde-discordchan-from-discord-logo", image:"", note:"Discord-logo Clyde fanart page on Newgrounds." },
    { id:"discord-cat-thing-5-5", source:"Newgrounds", title:"Discord Cat Thing 5 / 5", artist:"BreadinatoArts", tags:["clyde","discord","catgirl","furry","fanart"], url:"https://www.newgrounds.com/art/view/breadinatoarts/discord-cat-thing-5-5", image:"", note:"Verified Newgrounds entry explicitly tagged clyde and discord; the source page describes it as not NSFW." },
    { id:"discord-cat-thing-1-5", source:"Newgrounds", title:"Discord Cat Thing 1 / 5", artist:"BreadinatoArts", tags:["clyde","discord","catgirl","furry","fanart"], url:"https://www.newgrounds.com/art/view/breadinatoarts/discord-cat-thing-1", image:"", note:"Verified Newgrounds Clyde/Discord artwork; the page contains the first image in a five-image Discord-cat set." },
    { id:"discord-logo-wip", source:"DeviantArt", title:"Discord APP logo", artist:"Efluviosart", tags:["clyde","discord","discord-logo","fanart","furry"], url:"https://www.deviantart.com/efluviosart/art/Discord-APP-logo-995446093", image:"", note:"Verified DeviantArt fan art based on the Discord application logo; the page reports a 2500x2500 image." },
    { id:"discord-official-clyde", source:"Discord Official", title:"Clyde the Discord Mascot", artist:"Discord", tags:["clyde","discord","official","mascot"], url:"https://discord.com/blog/happy-blurpthday-to-discord-a-place-for-everything-you-can-imagine", image:"", note:"Official Discord article containing multiple Clyde design images and the mascot's history." },
    { id:"wallpapers-clyde-headache", source:"Wallpapers.com", title:"Discord Clyde With Headache Art Wallpaper", artist:"tarakan.ua", tags:["clyde","discord","wallpaper","art","logo"], url:"https://wallpapers.com/wallpapers/discord-clyde-with-headache-art-bby4q65ndyfgdzjq.html", image:"https://wallpapers.com/images/hd/discord-clyde-with-headache-art-bby4q65ndyfgdzjq.jpg", note:"Verified Wallpapers.com page with an actual Clyde image preview. Attribution is required by the page." },
    { id:"wallpapers-clyde-hazy", source:"Wallpapers.com", title:"Discord Clyde Hazy Art Wallpaper", artist:"umka.katya", tags:["clyde","discord","wallpaper","art","logo","hazy"], url:"https://wallpapers.com/wallpapers/discord-clyde-hazy-art-43m1dzspfmstxj69.html", image:"https://wallpapers.com/images/hd/discord-clyde-hazy-art-43m1dzspfmstxj69.jpg", note:"Verified Wallpapers.com Clyde artwork page with an image preview. Attribution is required by the page." },
    { id:"wallpapers-neon-clyde", source:"Wallpapers.com", title:"Neon Discord Clyde Icon Wallpaper", artist:"tjizzlenigga", tags:["clyde","discord","wallpaper","neon","logo","art"], url:"https://wallpapers.com/wallpapers/neon-discord-clyde-icon-kbey8jag3x4f3xqk.html", image:"https://wallpapers.com/images/hd/neon-discord-clyde-icon-kbey8jag3x4f3xqk.jpg", note:"Verified Wallpapers.com page with a Clyde icon image preview. Attribution is required by the page." }
  ]
};
