window.CLYDE_DATA = {
  source: "Newgrounds",
  verified: [
    { id:"clyde-discord-inuzu", title:"Clyde (Discord)", artist:"Inuzu", tags:["clyde","discord","fanart","illustration"], url:"https://www.newgrounds.com/art/view/inuzu/clyde-discord", image:"https://art.ngfiles.com/images/2231000/2231669_inuzu_clyde-discord.jpg?f1639141665=", note:"Clyde artwork specifically titled Clyde (Discord)." },
    { id:"discord-samrunner", title:"Discord", artist:"SamRunner", tags:["clyde","discord","fanart","furry","furry-art","darkmode","lightmode"], url:"https://www.newgrounds.com/art/view/samrunner/discord", image:"https://art.ngfiles.com/images/2531000/2531864_samrunner_discord.png?f1653146054=", note:"Clyde Discord fanart with dark-mode and light-mode concepts." },
    { id:"anthro-clyde", title:"Anthro Clyde", artist:"LiquidCrystalBunny", tags:["anthro","discord","furry","furry-art","pixel-art"], url:"https://www.newgrounds.com/art/view/zaxolotl/anthro-clyde", image:"", note:"Anthro/furry interpretation of Discord's Clyde. Open the original page for the artwork." },
    { id:"discord-furry-lol", title:"Discord furry lol", artist:"DatsFunny", tags:["clyde","discord","discord-clyde","discord-furry"], url:"https://www.newgrounds.com/art/view/datsfunny/discord-furry-lol", image:"", note:"Newgrounds artwork explicitly tagged clyde, discord, discord-clyde, and discord-furry." },
    { id:"clyde-old", title:"Clyde (old)", artist:"chomperChomp", tags:["clyde","discord","mascot","illustration"], url:"https://www.newgrounds.com/art/view/chomperchomp/clyde", image:"", note:"Older Discord Clyde mascot artwork. The Newgrounds page contains an image." },
    { id:"robot-girl-clyde", title:"robot girl discord clyde", artist:"ItIsNowSoupTime", tags:["clyde","discord","robot","illustration"], url:"https://www.newgrounds.com/art/view/itisnowsouptime/robot-girl-discord-clyde", image:"https://art.ngfiles.com/images/834000/834311_itisnowsouptime_robot-girl-discord-clyde.webp", note:"Illustration explicitly titled around Discord Clyde; the Newgrounds page exposes an art image." },
    { id:"thanks-discord", title:"Thanks for the whole year (new discord server)", artist:"Nemuri18", tags:["clyde","clyde-discord","discord","discord-server"], url:"https://www.newgrounds.com/art/view/nemuri18/thanks-for-the-whole-year-new-discord-server", image:"", note:"Newgrounds artwork tagged with Clyde and Discord." },
    { id:"more-cat-discord", title:"More Cat of discoerddsdsds", artist:"BreadinatoArts", tags:["clyde-discord","discord"], url:"https://www.newgrounds.com/art/view/breadinatoarts/more-cat-of-discoerddsdsds", image:"", note:"Artwork tagged clyde-discord and discord on Newgrounds." },
    { id:"clyde-discordchan", title:"Clyde(discordchan from discord logo)", artist:"palmeritauwuy", tags:["clyde","discord","furry","cat","illustration"], url:"https://www.newgrounds.com/art/view/palmeritauwuy/clyde-discordchan-from-discord-logo", image:"", note:"Discord-logo Clyde fanart page on Newgrounds." }
  ]
};
