window.CLYDE_DATA = {
  source: "Multiple verified sources",
  verified: [
    { id:"clyde-discord-inuzu", source:"Newgrounds", title:"Clyde (Discord)", artist:"Inuzu", tags:["clyde","discord","fanart","illustration"], url:"https://www.newgrounds.com/art/view/inuzu/clyde-discord", image:"https://art.ngfiles.com/images/2231000/2231669_inuzu_clyde-discord.jpg?f1639141665=", note:"Clyde artwork specifically titled Clyde (Discord)." },
    { id:"discord-samrunner", source:"Newgrounds", title:"Discord", artist:"SamRunner", tags:["clyde","discord","fanart","furry","furry-art","darkmode","lightmode"], url:"https://www.newgrounds.com/art/view/samrunner/discord", image:"https://art.ngfiles.com/images/2531000/2531864_samrunner_discord.png?f1653146054=", note:"Clyde Discord fanart with dark-mode and light-mode concepts." },
    { id:"anthro-clyde", source:"Newgrounds", title:"Anthro Clyde", artist:"LiquidCrystalBunny", tags:["anthro","discord","furry","furry-art","pixel-art"], url:"https://www.newgrounds.com/art/view/zaxolotl/anthro-clyde", image:"", note:"Anthro/furry interpretation of Discord's Clyde. Open the original page for the artwork." },
    { id:"discord-furry-lol", source:"Newgrounds", title:"Discord furry lol", artist:"DatsFunny", tags:["clyde","discord","discord-clyde","discord-furry"], url:"https://www.newgrounds.com/art/view/datsfunny/discord-furry-lol", image:"", note:"Newgrounds artwork explicitly tagged clyde, discord, discord-clyde, and discord-furry." },
    { id:"clyde-old", source:"Newgrounds", title:"Clyde (old)", artist:"chomperChomp", tags:["clyde","discord","mascot","illustration"], url:"https://www.newgrounds.com/art/view/chomperchomp/clyde", image:"", note:"Older Discord Clyde mascot artwork. The Newgrounds page contains an image." },
    { id:"robot-girl-clyde", source:"Newgrounds", title:"robot girl discord clyde", artist:"ItIsNowSoupTime", tags:["clyde","discord","robot","illustration"], url:"https://www.newgrounds.com/art/view/itisnowsouptime/robot-girl-discord-clyde", image:"https://art.ngfiles.com/images/834000/834311_itisnowsouptime_robot-girl-discord-clyde.webp", note:"Illustration explicitly titled around Discord Clyde; the Newgrounds page exposes an art image." },
    { id:"thanks-discord", source:"Newgrounds", title:"Thanks for the whole year (new discord server)", artist:"Nemuri18", tags:["clyde","clyde-discord","discord","discord-server"], url:"https://www.newgrounds.com/art/view/nemuri18/thanks-for-the-whole-year-new-discord-server", image:"", note:"Newgrounds artwork tagged with Clyde and Discord." },
    { id:"more-cat-discord", source:"Newgrounds", title:"More Cat of discoerddsdsds", artist:"BreadinatoArts", tags:["clyde-discord","discord"], url:"https://www.newgrounds.com/art/view/breadinatoarts/more-cat-of-discoerddsdsds", image:"", note:"Artwork tagged clyde-discord and discord on Newgrounds." },
    { id:"clyde-discordchan", source:"Newgrounds", title:"Clyde(discordchan from discord logo)", artist:"palmeritauwuy", tags:["clyde","discord","furry","cat","illustration"], url:"https://www.newgrounds.com/art/view/palmeritauwuy/clyde-discordchan-from-discord-logo", image:"", note:"Discord-logo Clyde fanart page on Newgrounds." },
    { id:"discord-cat-thing-5-5", source:"Newgrounds", title:"Discord Cat Thing 5 / 5", artist:"BreadinatoArts", tags:["clyde","discord","catgirl","furry","fanart"], url:"https://www.newgrounds.com/art/view/breadinatoarts/discord-cat-thing-5-5", image:"", note:"Verified Newgrounds entry explicitly tagged clyde and discord; the source page describes it as not NSFW." },
    { id:"discord-logo-wip", source:"DeviantArt", title:"Discord Logo WIP", artist:"SoggieCereal", tags:["clyde","discord","discord-logo","fanart","logo"], url:"https://www.deviantart.com/soggiecereal/art/Discord-Logo-WIP-850329577", image:"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c2d8e594-1014-46dd-a408-dfe75b6fcae2/de29ii1-8147025b-7760-4137-aec1-13f38f66323d.png/v1/fill/w_600%2Ch_425/discord_logo_wip_by_soggiecereal_de29ii1-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NDI1IiwicGF0aCI6Ii9mL2MyZDhlNTk0LTEwMTQtNDZkZC1hNDA4LWRmZTc1YjZmY2FlMi9kZTI5aWkxLTgxNDcwMjViLTc3NjAtNDEzNy1hZWMxLTEzZjM4ZjY2MzIzZC5wbmciLCJ3aWR0aCI6Ijw9NjAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.tggXeEFtPyUAIIgko_IspWv0Uhx_XU9YSJZkNppP5pk", note:"Discord-logo fan art work-in-progress hosted on DeviantArt." },
    { id:"discord-official-clyde", source:"Discord Official", title:"Clyde the Discord Mascot", artist:"Discord", tags:["clyde","discord","official","mascot"], url:"https://support.discord.com/hc/en-us", image:"https://support.discord.com/hc/theming_assets/01JXZJRXD81XRPSZK0GWNZVCBN", note:"Official Clyde mascot artwork from Discord's support site." }
  ]
};
